### ISSUE TITLE
Generatate composite unique constraints

### ISSUE THREAD

**Issue by cacomop** [tiangolo/sqlmodel#114]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional
import datetime
from sqlmodel import SQLModel, Field

class User(SQLModel):
    id: int = Field(primary_key=True)
    name: str = Field(unique=True)
    lastname: str = Field(unique=True)
```

### Description

* create a User model
* create a unique constraint on (name, latname)

### Operating System

Windows

### SQLModel Version

0.0.3

### Python Version

3.8.6

**Comment by tadejsv** [comment]
Do this

```python
from typing import Optional
import datetime
from sqlalchemy import UniqueConstraint
from sqlmodel import SQLModel, Field

class User(SQLModel):
    __table_args__ = (UniqueConstraint("name", "lastname"), )

    id: int = Field(primary_key=True)
    name: str = Field(unique=True)
    lastname: str = Field(unique=True)

```

**Comment by cacomop** [comment]
it works! thank you a lot!

where did you find the solution?

**Comment by tadejsv** [comment]
Basically, the `SQLModel` can be treated as a subclass of SQLAlchemy's declarative `Base`, so everything that works there should work here as well.

Specifically, for `__table_args__`, see here: https://docs.sqlalchemy.org/en/14/orm/declarative_tables.html#orm-declarative-table-configuration

**Comment by DanLipsitt** [comment]
@northtree I think this would result in two independent constraints rather than a single composite constraint. In other words, it would only allow one record with a given first _or_ last name rather than a given first _and_ last name.

**Comment by northtree** [comment]
> @northtree I think this would result in two independent constraints rather than a single composite constraint. In other words, it would only allow one record with a given first _or_ last name rather than a given first _and_ last name.

If you just need one single composite unique constraint, you just need to define via `__table_args`

```
from typing import Optional
import datetime
from sqlalchemy import UniqueConstraint
from sqlmodel import SQLModel, Field

class User(SQLModel):
    __table_args__ = (UniqueConstraint("name", "lastname"), )

    id: int = Field(primary_key=True)
    name: str
    lastname: str

```

**Comment by productdevbook** [comment]
<img width="775" alt="CleanShot 2021-12-28 at 20 12 52@2x" src="https://user-images.githubusercontent.com/38668796/147590464-aad540b3-70c3-444b-9a02-9cefd76a13b3.png">

**Comment by clstaudt** [comment]
Whatever the reason for the change may be, I think that `Field(unique=True)` is by far more intuitive and pythonic than `Field(sa_column_kwargs={"unique": True})`.

**Comment by jramboz** [comment]
Sorry for the thread necromancy, but has `__table_args__` been removed from `SQLModel`? I'm attempting to do exactly this same thing (create a unique constraint on multiple columns), but I get an error:

```
>>> import models.forms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jramboz/dev/ludomanager/backend/models/forms.py", line 3, in <module>
    class LSForm(SQLModel, table=True):
  File "/Users/jramboz/dev/ludomanager/backend/models/forms.py", line 4, in LSForm
    __table_args__ (
    ^^^^^^^^^^^^^^
NameError: name '__table_args__' is not defined
```

It's also not recognized in VSCode. Has this behavior been changed? Is there something else I need to do/import to make `__table_args__` visible?
