### ISSUE TITLE
ERROR: Could not find a version that matches sqlalchemy2-stubs

### ISSUE THREAD

**Issue by jet10000** [tiangolo/sqlmodel#16]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
% pipenv install
Pipfile.lock (16c839) out of date, updating to (2bfea0)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 741, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 702, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 684, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 1397, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 835, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches sqlalchemy2-stubs (from sqlmodel==0.0.4->-r /var/folders/_d/pcm157vn4kg3mv8wvb37vy2w0000gn/T/pipenva49pmcxnrequirements/pipenv-qf_w3zcm-constraints.txt (line 2))
Skipped pre-versions: 0.0.1a1, 0.0.1a2, 0.0.1a3, 0.0.1a4, 0.0.1a4, 0.0.1a5, 0.0.1a5, 0.0.1a6, 0.0.1a6, 0.0.1a7, 0.0.1a7, 0.0.1a8, 0.0.1a8, 0.0.1a9, 0.0.1a9, 0.0.1a10, 0.0.1a10, 0.0.1a11, 0.0.1a11, 0.0.2a1, 0.0.2a1, 0.0.2a2, 0.0.2a2, 0.0.2a3, 0.0.2a3, 0.0.2a4, 0.0.2a4, 0.0.2a5, 0.0.2a5, 0.0.2a6, 0.0.2a6, 0.0.2a7, 0.0.2a7, 0.0.2a8, 0.0.2a8, 0.0.2a9, 0.0.2a9, 0.0.2a10, 0.0.2a10, 0.0.2a11, 0.0.2a11, 0.0.2a12, 0.0.2a12
There are incompatible versions in the resolved dependencies:
```

### Description

```
from typing import Optional

from sqlmodel import Field, Session, SQLModel, create_engine, select


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None


engine = create_engine("sqlite:///database.db")


with Session(engine) as session:

    statement = select(Hero).where(Hero.name == "Spider-Boy")

    hero = session.exec(statement).first()

    print(hero)

```

### Operating System

macOS

### SQLModel Version

Traceback (most recent call last):   File "<string>", line 1, in <module> ModuleNotFoundError: No module named 'sqlmodel'

### Python Version

python3 --version Python 3.9.6

**Comment by peterHoburg** [comment]
I think this is a pipenv issue. Pipenv is `Skipped pre-versions` for sqlalchemy2-stubs. All the sqlalchemy2-stubs are "pre-versions". You have to accept using them.

**Comment by sometato** [comment]
I'm running into this as well. I wonder if it'd work to add sqlalchemy2-stubs to the Pipfile, itself, as a workaround?

**Comment by tiangolo** [comment]
It seems this would be specific to Pipenv not being able to handle the dependencies properly, but that it could be solved that way, right? If that's the case you can then close this issue.

Also, just as a suggestion, try [Poetry](https://python-poetry.org/), it's quite good.
