### ISSUE TITLE
error when use list as generic with Relationship

### ISSUE THREAD

**Issue by phi-friday** [tiangolo/sqlmodel#238]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [ ] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [ ] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

from sqlmodel import Field, Relationship, SQLModel


class son_mother_link(SQLModel, table=True):
    son_id: Optional[int] = Field(None, foreign_key="son.id", primary_key=True)
    mother_id: Optional[int] = Field(None, foreign_key="mother.id", primary_key=True)


class son(SQLModel, table=True):
    id: Optional[int] = None
    name: str

    mothers: list["mother"] = Relationship(
        back_populates="sons", link_model=son_mother_link
    )


class mother(SQLModel, table=True):
    id: Optional[int] = None
    name: str

    sons: list[son] = Relationship(back_populates="mothers", link_model=son_mother_link)
```

### Description

example code -> Error!
```
Traceback (most recent call last):
  File "pydantic/validators.py", line 709, in pydantic.validators.find_validators
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../test.py", line 11, in <module>
    class son(SQLModel, table=True):
  File ".../.pyenv/versions/3.9.9/envs/.../lib/python3.9/site-packages/sqlmodel/main.py", line 342, in __init__
    temp_field = ModelField.infer(
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 728, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 778, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 539, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 801, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 718, in find_validators
RuntimeError: error checking inheritance of 'mother' (type: str)
```

if list -> typing.List, not Error.
```
from typing import List, Optional
from sqlmodel import Field, Relationship, SQLModel


class son_mother_link(SQLModel, table=True):
    son_id: Optional[int] = Field(None, foreign_key="son.id", primary_key=True)
    mother_id: Optional[int] = Field(None, foreign_key="mother.id", primary_key=True)


class son(SQLModel, table=True):
    id: Optional[int] = Field(None, primary_key=True)
    name: str

    mothers: List["mother"] = Relationship(
        back_populates="sons", link_model=son_mother_link
    )


class mother(SQLModel, table=True):
    id: Optional[int] = Field(None, primary_key=True)
    name: str

    sons: List[son] = Relationship(back_populates="mothers", link_model=son_mother_link)
```

if not use Relationship, not Error.
```
from typing import Optional
from sqlmodel import Field, SQLModel


class son(SQLModel, table=True):
    id: Optional[int] = Field(None, primary_key=True)
    name: str

    dummy: list[str]


class mother(SQLModel, table=True):
    id: Optional[int] = Field(None, primary_key=True)
    name: str

    dummy: list[str]
```

### Operating System

Linux

### Operating System Details

OS: Ubuntu 18.04.6 LTS x86_64
Kernel: 5.4.0-1065-azure
CPU: Intel Xeon E5-2673 v4 (2) @ 2.294GHz

### SQLModel Version

0.0.6

### Python Version

3.9.9

**Comment by phi-friday** [comment]
#228 It seems to have been caused by the same problem
