### ISSUE TITLE
Optional[Dict[str, str]] field handle error, (sqlite3.InterfaceError) Error binding parameter 4 - probably unsupported type.

### ISSUE THREAD

**Issue by mr-m0nst3r** [tiangolo/sqlmodel#241]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class TaskCreate(SQLModel):
    name: str
    report_id: UUID
    target: Optional[HttpUrl]
    version: str
    md5: Optional[Dict[str, str]]
    onsite: Optional[bool] = Field(default=False)
    envs: Optional[Dict[str, str]]

    # foreign key
    client_id: Optional[int] = Field(default=None, foreign_key="client.id")


@router.post("/", response_model=Task)
def create_tasks(
        *,
        db: Session = Depends(get_session),
        task_in: TaskCreate
):
    """
    Create a task.
    """
    db_task = Task.from_orm(task_in)
    db.add(db_task)
    db.commit()
    db.refresh(db_task)
    return db_task
```

### Description

```json
{
  "name": "task1",
  "report_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "target": "http://a.com",
  "version": "v1.0",
  "md5": {
    "app.zip": "1231231231231234"
  },
  "onsite": false,
  "envs": {
    "apache": "5.0"
  },
  "client_id": 0
}
```

In the docs, I'm trying to create task with the above data, but I find that it can't be created with `json` embeded, leading to the following error:
```
INFO:     127.0.0.1:56340 - "POST /tasks/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/m0nst3r/dev/py/tespla/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/m0nst3r/dev/py/tespla/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 4 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/m0nst3r/dev/py/tespla/venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/m0nst3r/dev/py/tespla/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/m0nst3r/dev/py/tespla/venv/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
......
 File "/Users/m0nst3r/dev/py/tespla/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/m0nst3r/dev/py/tespla/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/m0nst3r/dev/py/tespla/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 4 - probably unsupported type.
[SQL: INSERT INTO task (name, report_id, target, version, md5, onsite, envs, client_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('task1', '3fa85f6457174562b3fc2c963f66afa6', HttpUrl('http://a.com', scheme='http', host='a.com', tld='com', host_type='domain'), 'v1.0', {'app.zip': '1231231231231234'}, 0, {'apache': '5.0'}, 0)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)

```

But if I quote the embeded json to the following:
```json
{
  "name": "task1",
  "report_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "target": "http://a.com",
  "version": "v1.0",
  "md5": "{
    \"app.zip\": \"1231231231231234\"
  }",
  "onsite": false,
  "envs": "{
    \"apache\": \"5.0\"
  }",
  "client_id": 0
}
```
it's showing:
`INFO:     127.0.0.1:57231 - "POST /tasks/ HTTP/1.1" 422 Unprocessable Entity`

It only works when no embeded json inside, but I need the md5 and envs fields.

Appreciate!

### Operating System

macOS

### Operating System Details

```shell
pip freeze
anyio==3.4.0
arrow==1.2.1
asgiref==3.4.1
binaryornot==0.4.4
certifi==2021.10.8
chardet==4.0.0
charset-normalizer==2.0.10
click==8.0.3
cookiecutter==1.7.3
dnspython==2.2.0
email-validator==1.1.3
fastapi==0.70.1
h11==0.12.0
httptools==0.3.0
idna==3.3
Jinja2==3.0.3
jinja2-time==0.2.0
jose==1.0.0
MarkupSafe==2.0.1
poyo==0.5.0
pydantic==1.8.2
python-dateutil==2.8.2
python-dotenv==0.19.2
python-slugify==5.0.2
PyYAML==6.0
requests==2.27.1
six==1.16.0
sniffio==1.2.0
SQLAlchemy==1.4.29
sqlalchemy2-stubs==0.0.2a19
sqlmodel==0.0.6
starlette==0.16.0
text-unidecode==1.3
typing_extensions==4.0.1
urllib3==1.26.8
uvicorn==0.16.0
uvloop==0.16.0
watchgod==0.7
websockets==10.1
```

### SQLModel Version

0.0.6

### Python Version

Python 3.9.9

**Comment by byrman** [comment]
Your example code is incomplete without your `Task` model.

**Comment by mr-m0nst3r** [comment]
Hi @byrman :

sorry, here's the Task model:
```
class Task(TaskCreate, table=True):
    """
    Task/Project table
    """
    id: Optional[int] = Field(default=None, primary_key=True)

    # Relationships
    client: Optional[Client] = Relationship(back_populates="tasks")
    vulns: List["Vuln"] = Relationship(back_populates="task")

```

**Comment by byrman** [comment]
You are better off providing a minimal example that reproduces the error instead of pasting your application code: `Client` and `Vuln` are missing now, making it hard for people to reproduce your issue.

The problem seems to be that you are trying to save a dictionary into a database text field. You should find a way to translate between the two or declare a different column type. With PostgreSQL, for example, you could do this and get the translation for free:
```
from typing import Dict, Optional
from sqlmodel import JSON, Column, Field


class TaskCreate(SQLModel):
    md5: Optional[Dict[str, str]] = Field(sa_column=Column(JSON))
```

**Comment by byrman** [comment]
Writing a custom type that handles this conversion does not appear to be too hard either: https://docs.sqlalchemy.org/en/14/core/custom_types.html#augmenting-existing-types.
```
import json
import sqlalchemy.types as types

class JsonType(types.TypeDecorator):
    impl = types.TEXT

    def process_bind_param(self, value, dialect):
        return json.dumps(value)

    def process_result_value(self, value, dialect):
        return json.loads(value)
```

**Comment by mr-m0nst3r** [comment]
Hi guys,

I'll look into the above to see whether I can figure it out.

But now, I'm lost. I'm searching codes leads to the intended data structure, and can't find results on the internet.

I adjusted the code, since the frontend need more structural data, as follows:
```
class Hashes(SQLModel):
    arch_name: str
    arch_hash: str


class Envs(SQLModel):
    env_name: str
    env_version: str


class Task(SQLModel, table=True):
    """
    Task/Project table
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    report_id: UUID
    target: Optional[HttpUrl]
    version: str
    hashes: Optional[List[Hashes]] = Field(sa_column=Column(ARRAY(JSON)))
    onsite: Optional[bool] = Field(default=False)
    envs: Optional[List[Envs]] = Field(sa_column=Column(ARRAY(JSON)))

    # foreign key
    client_id: Optional[int] = Field(default=None, foreign_key="client.id")
    # Relationships
    client: Optional[Client] = Relationship(back_populates="tasks")
    vulns: List["Vuln"] = Relationship(back_populates="task")
```

error:
```
sqlalchemy.exc.CompileError: (in table 'task', column 'hashes'): Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0x105369ac0> can't render element of type ARRAY
```

The data structure intended is as follow:
```
{
  "name": "task1",
  "report_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "target": "http://a.com",
  "version": "v1.0",
  "md5": [
    {
      "arch_name": "a.zip",
      "arch_hash": "123123123123123123"
    },
    {
      "arch_name": "b.zip",
      "arch_hash": "456456456456456456"
    }
  ],
  "onsite": false,
  "envs": [
    {
      "env_name": "java",
      "env_version": "1.7"
    },
    {
      "env_name": "tomcat",
      "env_version": "6.5"
    }
  ],
  "client_id": 1
}
```

Thanks @byrman for the guidence, I'll come back after had a try.

**Comment by mr-m0nst3r** [comment]
> You are better off providing a minimal example that reproduces the error instead of pasting your application code: `Client` and `Vuln` are missing now, making it hard for people to reproduce your issue.
> 
> The problem seems to be that you are trying to save a dictionary into a database text field. You should find a way to translate between the two or declare a different column type. With PostgreSQL, for example, you could do this and get the translation for free:
> 
> ```
> from typing import Dict, Optional
> from sqlmodel import JSON, Column, Field
> 
> 
> class TaskCreate(SQLModel):
>     md5: Optional[Dict[str, str]] = Field(sa_column=Column(JSON))
> ```

I did fixed the original error by this way.

But as the above shows, I met some new needs. Since they're basically the same type of problem, I'm not posting on new issues.

**Comment by byrman** [comment]
Are you sure ARRAY is supported for sqlite? https://www.sqlite.org/datatype3.html

**Comment by mr-m0nst3r** [comment]
I'll set up a mysql server to test it out, thanks. 

by the way, 

```
class Task(SQLModel, table=True):
    """
    Task/Project table
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    report_id: UUID
    target: Optional[HttpUrl]
    version: str
    # hashes: Optional[List[Hashes]] = Field(sa_column=Column(ARRAY(String)))
    hashes: Optional[List[Hashes]] = Field(sa_column=Column(JSON))
    onsite: Optional[bool] = Field(default=False)
    # envs: Optional[List[Envs]] = Field(sa_column=Column(ARRAY(String)))
    envs: Optional[List[Envs]] = Field(sa_column=Column(JSON))

    class Config:
        arbitrary_types_allowed = True
```

with that `config` class, the database is created, but when I'm `POST` data, the error is as following:
```
 raise TypeError(f'Object of type {o.__class__.__name__} '
sqlalchemy.exc.StatementError: (builtins.TypeError) Object of type Hashes is not JSON serializable
[SQL: INSERT INTO task (hashes, envs, name, report_id, target, version, onsite, client_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'hashes': [Hashes(arch_name='string', arch_hash='string')], 'target': HttpUrl('http://a.com', scheme='http', host='a.com', tld='com', host_type='dom ... (44 characters truncated) ... version='string')], 'report_id': UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6'), 'version': 'string', 'onsite': True, 'client_id': 1, 'name': 'string'}]]

```

I'll first check mysql and postgresql to see whether the `ARRAY(JSON)` works.
come back later.

**Comment by byrman** [comment]
I don't fully understand what you're trying to achieve: Task - Env is a standard one-to-many relation, isn't it? Why using ARRAY to model this?

**Comment by mr-m0nst3r** [comment]
Tested on mysql, same error:
```
raise exception
sqlalchemy.exc.CompileError: (in table 'task', column 'hashes'): Compiler <sqlalchemy.dialects.mysql.base.MySQLTypeCompiler object at 0x1059627c0> can't render element of type ARRAY
```

for your question above, I need to `POST` the following data:
```
{
  "name": "task1",
  "report_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "target": "http://a.com",
  "version": "v1.0",
  "hashes": [
    {
      "arch_name": "a.zip",
      "arch_hash": "123123123123123123"
    },
    {
      "arch_name": "b.zip",
      "arch_hash": "456456456456456456"
    }
  ],
  "onsite": false,
  "envs": [
    {
      "env_name": "java",
      "env_version": "1.7"
    },
    {
      "env_name": "tomcat",
      "env_version": "6.5"
    }
  ],
  "client_id": 1
}

```

the `hashes` and `envs` are type `json array`, how should I modify the classes then?

**Comment by mr-m0nst3r** [comment]
I changed to not to use ARRAY, but still got an error, would you pls help me out?

the model:
```
class Hashes(SQLModel):
    arch_name: str
    arch_hash: str


class Envs(SQLModel):
    env_name: str
    env_version: str

class Task(SQLModel, table=True):
    """
    Task/Project table
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    report_id: UUID
    target: Optional[HttpUrl]
    version: str
    hashes: Optional[List[Hashes]] = Field(sa_column=Column(JSON))
    onsite: Optional[bool] = Field(default=False)
    envs: Optional[List[Envs]] = Field(sa_column=Column(JSON))

    # foreign key
    client_id: Optional[int] = Field(default=None, foreign_key="client.id")
    # Relationships
    client: Optional[Client] = Relationship(back_populates="tasks")
    vulns: List["Vuln"] = Relationship(back_populates="task")
```

when `POST` the following the data, I got error as below:
``` error-message
sqlalchemy.exc.StatementError: (builtins.TypeError) Object of type Hashes is not JSON serializable
[SQL: INSERT INTO task (hashes, envs, name, report_id, target, version, onsite, client_id) VALUES (%(hashes)s, %(envs)s, %(name)s, %(report_id)s, %(target)s, %(version)s, %(onsite)s, %(client_id)s)]
[parameters: [{'onsite': False, 'report_id': UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6'), 'hashes': [Hashes(arch_name='a.zip', arch_hash='123123123123123123'), Ha ... (151 characters truncated) ... nv_version='6.5')], 'target': HttpUrl('http://a.com', scheme='http', host='a.com', tld='com', host_type='domain'), 'version': 'v1.0', 'client_id': 1}]]
```

```json
{
  "name": "task1",
  "report_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "target": "http://a.com",
  "version": "v1.0",
  "hashes": [
    {
      "arch_name": "a.zip",
      "arch_hash": "123123123123123123"
    },
    {
      "arch_name": "b.zip",
      "arch_hash": "456456456456456456"
    }
  ],
  "onsite": false,
  "envs": [
    {
      "env_name": "java",
      "env_version": "1.7"
    },
    {
      "env_name": "tomcat",
      "env_version": "6.5"
    }
  ],
  "client_id": 1
}

```

appreciate!

**Comment by mr-m0nst3r** [comment]
hi @byrman ,

it's strange, if i don't use the custom class, it's success:
```
hashes: Optional[List[Dict[str, str]]] = Field(sa_column=Column(JSON))
onsite: Optional[bool] = Field(default=False)
envs: Optional[List[Dict[str, str]]] = Field(sa_column=Column(JSON))
```

as the above shows, I use `Dict[str,str]` to replace custome `hashes` and `envs`,

it's working now, but it just lost some verification, I guess, I can't fix the keys because they're user input.

**Comment by byrman** [comment]
Yes, this is the first of the two design options I mentioned. If you want to try the second as well, you should get rid of the JSON fields and model it as a standard relationship to your `Hashes` and `Envs` models.

**Comment by mr-m0nst3r** [comment]
Thank you @byrman ! You saved a beginner's life!
