### ISSUE TITLE
How to use `with_variant` in SQLModel table definition ?

### ISSUE THREAD

**Issue by aussetg** [tiangolo/sqlmodel#276]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional, Dict, Any, List

from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, SQLModel, JSON, Column, Relationship, Enum
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import Engine
from sqlmodel import create_engine

JSON_variant = JSON().with_variant(postgresql.JSONB, 'postgresql') # Doesn't work woth SQLModel?

class TestTable(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    config: dict[str, Any] = Field(index=False, sa_column=Column(JSON_variant))


engine = create_engine("sqlite:///")
SQLModel.metadata.create_all(engine)
```

### Description

I need to use `jsonb` with PostgreSQL in order to use `==` comparisons and `json` in sqlite.

The SQL Alchemy solution would be to use 

`JSON_variant = JSON().with_variant(postgresql.JSONB, 'postgresql')`

as the type but in SQL Model this results in a recursion overflow:

```python
    use_type = create_model(original_type.__name__, __base__=original_type)
pydantic/main.py:972: in pydantic.main.create_model
    ???
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib/python3.9/site-packages/sqlmodel/main.py:277: in __new__
    new_cls = super().__new__(cls, name, bases, dict_used, **config_kwargs)
pydantic/main.py:148: in pydantic.main.ModelMetaclass.__new__
    ???
pydantic/utils.py:655: in pydantic.utils.smart_deepcopy
    ???
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
../../../../../.cache/pypoetry/virtualenvs/monitoringdashboard-C_SCbHCl-py3.9/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py:1313: in __getattr__
    return getattr(self.impl, key)
E   RecursionError: maximum recursion depth exceeded
!!! Recursion error detected, but an error occurred locating the origin of recursion.
  The following exception happened when comparing locals in the stack frame:
    ArgumentError: SQL expression element or literal value expected, got Table('drift', MetaData(), Column('prediction_type', Enum('AUTOMATIC', 'MANUAL', name='predictiontype'), table=<drift>), Column('drift_type', Enum('COVARIATE', 'LABEL', 'CONCEPT', 'PREDICTION', 'DATA_QUALITY', name='drifttype'), table=<drift>), Column('detail', Variant(), table=<drift>), Column('id', Integer(), table=<drift>, primary_key=True), Column('date_start', Date(), table=<drift>, nullable=False), Column('date_end', Date(), table=<drift>, nullable=False), Column('global_drift', Boolean(), table=<drift>, nullable=False), Column('metric_id', Integer(), ForeignKey('metric.id'), table=<drift>), Column('model_id', Integer(), ForeignKey('model.id'), table=<drift>), schema=None). To create a column expression from a FROM clause row as a whole, use the .table_valued() method.
  Displaying first and last 10 stack frames out of 952.
```

Is there any workaround in SQL Model ?

### Operating System

Linux

### Operating System Details

Fedora 35
Python 3.9
Poetry Virtualenv

### SQLModel Version

0.0.6

### Python Version

3.9.10

**Comment by espdev** [comment]
@aussetg 

This is not a FastAPI issue. Any model inheritance raises "maximum recursion depth exceeded" error.

A minimal example to reproduce:

```python
from sqlalchemy import Column, JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import SQLModel, Field

JsonVariant = JSONB().with_variant(JSON, "sqlite")


class A(SQLModel):
    a: dict | None = Field(None, sa_column=Column(JsonVariant))


class B(A):
    pass
```

<details>
  <summary>Recursion error traceback</summary>

```
Traceback (most recent call last):
  File "scratch_51.py", line 12, in <module>
    class B(A):
  File "python3.10/site-packages/sqlmodel/main.py", line 272, in __new__
    new_cls = super().__new__(cls, name, bases, dict_used, **config_kwargs)
  File "pydantic/main.py", line 138, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 693, in pydantic.utils.smart_deepcopy
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 211, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 211, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 211, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 211, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 272, in _reconstruct
    if hasattr(y, '__setstate__'):
  File "python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1486, in __getattr__
    return getattr(self.impl, key)
  File "python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1486, in __getattr__
    return getattr(self.impl, key)
  File "python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1486, in __getattr__
    return getattr(self.impl, key)
  [Previous line repeated 967 more times]
RecursionError: maximum recursion depth exceeded
```
</details>

I think the issue should be reopened.

**Comment by espdev** [comment]
The problem is that the Variant object cannot be copied via deepcopy (deepcopy is used in Pydantic under the hood):

```python
import copy

from sqlalchemy import Column, JSON
from sqlalchemy.dialects.postgresql import JSONB

JsonVariant = JSONB().with_variant(JSON, "sqlite")

copy.deepcopy(JsonVariant)  # <-- recursion error
```

There is the issue in SQLAlcheme in `Variant` type.
