### ISSUE TITLE
SQLModel class cannot be extended with non-Pydantic bases

### ISSUE THREAD

**Issue by jtv8** [tiangolo/sqlmodel#348]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from sqlmodel import SQLModel
from typing import Generic, TypeVar

T = TypeVar("T")

class ExtendedSQLModel(SQLModel, Generic[T]):
    pass
```

### Description

SQLModel cannot be extended with bases that are not a subclass of `pydantic.BaseModel`, because `SQLModelMetaclass.__init__` expects certain class attributes to be present on all bases. Extending SQLModel in this way may be useful if you want to make use of generics or mixins to extend its functionality.

**Expected behavior:**

I would expect the code snippet above to create a subclass without error, similar to this example using `pydantic.BaseModel`:

```
from pydantic import BaseModel
from typing import Generic, TypeVar

T = TypeVar("T")

class ExtendedBaseModel(BaseModel, Generic[T]):
    pass
```

**Actual behavior:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\sqlmodel\main.py", line 327, in __init__
    config = getattr(base, "__config__")
AttributeError: type object 'Generic' has no attribute '__config__'
```

### Operating System

Windows

### SQLModel Version

0.0.6

### Python Version

3.8.3

### Additional Context

**Workaround:**

You can work around this issue by mixing the desired class into a subclass of `pydantic.BaseModel` before mixing it in to your `SQLModel` subclass:

```
from pydantic import BaseModel
from sqlmodel import SQLModel
from typing import Generic, TypeVar

T = TypeVar("T")

class ExtendedBaseModel(BaseModel, Generic[T]):
    pass

class ExtendedSQLModel(SQLModel, ExtendedBaseModel):
    pass
```

**Suggested fix:**

Rewrite any lines that reference attributes from bases to handle the case where that attribute doesn't exist, e.g. change `main.py:326` from:
```
            config = getattr(base, "__config__")
```
to:
```
            config = getattr(base, "__config__", None)
```

**Comment by byrman** [comment]
https://github.com/tiangolo/sqlmodel/pull/256/files

**Comment by jtv8** [comment]
That will do it!

**Comment by jpmckinney** [comment]
I think this was resolved in fa2f178b8abee3e58b490bbfc0c7a7df966a1fe9

https://github.com/tiangolo/sqlmodel/blob/b892504141c842975b7a30156ab21755719e1d31/sqlmodel/_compat.py#L402

**Comment by YuriiMotov** [comment]
Resolved!

https://github.com/fastapi/sqlmodel/blob/e8f87e62e99831d26d15e4c938ff205d63ea3990/sqlmodel/_compat.py#L431
https://github.com/fastapi/sqlmodel/blob/e8f87e62e99831d26d15e4c938ff205d63ea3990/sqlmodel/_compat.py#L129
