### ISSUE TITLE
Support discriminated union

### ISSUE THREAD

**Issue by wholmen** [tiangolo/sqlmodel#356]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [ ] I commit to help with one of those options 👆

### Example Code

```python
from typing import Literal, Union, Optional
from sqlmodel import SQLModel, Field


class Bar(SQLModel):
    class_type: Literal["bar"] = "bar"
    name: str


class Foo(SQLModel):
    class_type: Literal["foo"] = "foo"
    name: str
    id: Optional[int]


class FooBar(SQLModel, table=True):
    id: int = Field(default=None, primary_key=True)
    data: Union[Foo, Bar] = Field(discriminator="class_type")
```

### Description

* No support for Pydantic 1.9's implementation of discriminated union

### Wanted Solution

Would like to have support for discriminated union in SQLModel-classes

### Wanted Code

```python
from typing import Literal, Union, Optional
from sqlmodel import SQLModel, Field


class Bar(SQLModel):
    class_type: Literal["bar"] = "bar"
    name: str


class Foo(SQLModel):
    class_type: Literal["foo"] = "foo"
    name: str
    id: Optional[int]


class FooBar(SQLModel, table=True):
    id: int = Field(default=None, primary_key=True)
    data: Union[Foo, Bar] = Field(discriminator="class_type")
```

### Operating System

Linux

### SQLModel Version

0.0.6

### Python Version

3.10.4

### Additional Context

Pydantic has added support for discrimated unions, something I use in my project with Pydantic + SQLAlchemy. 

I want to switch to SQLModel, but cannot switch before discriminated unions

**Comment by ljluestc** [comment]
from sqlmodel import SQLModel, Field, Relationship
from typing import Optional


class Base(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    class_type: str


class Bar(Base):
    __mapper_args__ = {"polymorphic_identity": "bar"}
    name: str


class Foo(Base):
    __mapper_args__ = {"polymorphic_identity": "foo"}
    name: str


class FooBar(SQLModel, table=True):
    id: int = Field(default=None, primary_key=True)
    data: Relationship[Base] = Field(discriminator="class_type")


# Create instances of Bar and Foo
bar_instance = Bar(name="My Bar")
foo_instance = Foo(name="My Foo")

# Create instance of FooBar with either a Bar or Foo instance
foobar_instance = FooBar(data=bar_instance)  # Or Foo instance

print(bar_instance)
print(foo_instance)
print(foobar_instance)

**Comment by tiangolo** [comment]
Support for this was added in https://github.com/tiangolo/sqlmodel/pull/440

You will be able to use it in the next version: `0.0.10` 🎉 

```python
from typing import Union

from sqlmodel import Field, SQLModel
from typing_extensions import Literal


class Cat(SQLModel):
    pet_type: Literal["cat"]
    meows: int


class Dog(SQLModel):
    pet_type: Literal["dog"]
    barks: float


class Lizard(SQLModel):
    pet_type: Literal["reptile", "lizard"]
    scales: bool


class Model(SQLModel):
    pet: Union[Cat, Dog, Lizard] = Field(..., discriminator="pet_type")
    n: int
```

**Comment by stuartaxonHO** [comment]
I wasn't able to get this working, I'm not sure it works in 0.0.27 ?

**Comment by YuriiMotov** [comment]
> I wasn't able to get this working, I'm not sure it works in 0.0.27 ?

Do you have MRE?

**Comment by stuartaxonHO** [comment]
I tried the example above with Cat, Dog, Lizard, Model.

None of the tables in the above example have `table=True`, so I added that to `Model` and ran alembic and I get:  

```python
214, in get_sa_type_from_type_annotation
    raise ValueError(
ValueError: Cannot have a (non-optional) union as a SQLAlchemy field
```

Full traceback
```python
% alembic revision --autogenerate -m "Initial schema."                           
Traceback (most recent call last):
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/bin/alembic", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/alembic/config.py", line 1033, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/alembic/config.py", line 1023, in main
    self.run_cmd(cfg, options)
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/alembic/config.py", line 957, in run_cmd
    fn(
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/alembic/command.py", line 309, in revision
    script_directory.run_env()
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/alembic/script/base.py", line 545, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 116, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 136, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/db/alembic/env.py", line 30, in <module>
    from db.models import *
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/db/models/__init__.py", line 3, in <module>
    from .rag_data import RAGDocument
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/db/models/rag_data.py", line 61, in <module>
    class Model(SQLModel, table=True):
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/sqlmodel/main.py", line 565, in __new__
    col = get_column_from_field(v)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/sqlmodel/main.py", line 714, in get_column_from_field
    sa_type = get_sqlalchemy_type(field)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/sqlmodel/main.py", line 658, in get_sqlalchemy_type
    type_ = get_sa_type_from_field(field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/sqlmodel/_compat.py", line 229, in get_sa_type_from_field
    return get_sa_type_from_type_annotation(type_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stuart.axon/projects/work/aim-asylum-trial/.venv/lib/python3.12/site-packages/sqlmodel/_compat.py", line 214, in get_sa_type_from_type_annotation
    raise ValueError(
ValueError: Cannot have a (non-optional) union as a SQLAlchemy field
```

**Comment by stuartaxonHO** [comment]
Apologies, this does seem to work after all.
