### ISSUE TITLE
"TypeError: Boolean value of this clause is not defined" with Enum column

### ISSUE THREAD

**Issue by TheManchineel** [tiangolo/sqlmodel#401]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from enum import Enum
from typing import Optional
from uuid import UUID

from sqlmodel import Column, SQLModel, Field
from sqlmodel import Enum as EnumField

class LocationType(str, Enum):
    A = "A"
    B = "B"
    C = "C"


class Location(SQLModel, table=True):
    __tablename__ = "locations"
    __table_args__ = {"schema": "my_schema"}
    uuid: Optional[UUID] = Field(default=None, primary_key=True)
    location_type: LocationType = Column(EnumField(LocationType))
    name: str
    description: str
    x: int
    y: int
    z: int
    additional_info: Optional[str] = None
```

### Description

* Create a LocationType Enum that allows three types of location (e.g. "A", "B", "C")
* Create a Location model with a location_type Column
* The following error appears:

```
Traceback (most recent call last):
  File "/Users/manchineel/Desktop/test.py", line 15, in <module>
    class Location(SQLModel, table=True):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sqlmodel/main.py", line 277, in __new__
    new_cls = super().__new__(cls, name, bases, dict_used, **config_kwargs)
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 528, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField._set_default_and_type
  File "pydantic/fields.py", line 422, in pydantic.fields.ModelField.get_default
  File "pydantic/utils.py", line 652, in pydantic.utils.smart_deepcopy
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 589, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
```

Maybe I'm doing something completely wrong. How would I set up an `Enum` column properly?

### Operating System

macOS

### SQLModel Version

0.0.6

### Python Version

Python 3.10.2

**Comment by meirdev** [comment]
You should use the Field class to define your fields:

```python
location_type: LocationType = Field(sa_column=EnumField(LocationType))
```

**Comment by TheManchineel** [comment]
This worked, thank you!
