### ISSUE TITLE
Preparing for Pydantic v2 release

### ISSUE THREAD

**Issue by bpenteado** [tiangolo/sqlmodel#532]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# any sqlmodel code is ok, providing that the development version of Pydantic v2 is installed (local or direct repo installation)

import SQLModel
```

### Description

After locally installing Pydantic v2 (main development branch)... :
```
>> python -c "import pydantic; print(pydantic.__version__)"
2.0.0.dev0
```

... SQLModel breaks at import time:

```
>> python -c "import sqlmodel"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bpenteado/opt/miniconda3/envs/lamin-dev/lib/python3.9/site-packages/sqlmodel/__init__.py", line 137, in <module>
    from .main import SQLModel as SQLModel
  File "/Users/bpenteado/opt/miniconda3/envs/lamin-dev/lib/python3.9/site-packages/sqlmodel/main.py", line 27, in <module>
    from pydantic.errors import ConfigError, DictError
ImportError: cannot import name 'ConfigError' from 'pydantic.errors' (/Users/bpenteado/laminlabs/pydantic/pydantic/errors.py)
```

Is there any roadmap or planning for preparing SQLModel for Pydantic V2?

This is not a request per se, but a simple inquiry as was done in the two issues below. Hopefully it serves as a watcher/tracker for this key transition:
-  [Open Bugs and Future of SQLModel](https://github.com/tiangolo/sqlmodel/issues/409) (issue in SQLModel)
- [Prepare for Pydantic V2 release](https://github.com/tiangolo/fastapi/issues/5806) (issue in FastAPI)

### Operating System

Linux, Windows, macOS, Other

### SQLModel Version

0.0.8

### Python Version

3.9.12

**Comment by antont** [comment]
FastAPI's Pydantic v2 support seems quite complete now, the CI now runs both with v1 and v2. I didn't look more closely though.

Perhaps now is a good time to check how it would go with SQLModel and FastAPI with Pydantic v2. Has anyone taken a look?

https://github.com/tiangolo/fastapi/pull/9688

**Comment by lfvarela** [comment]
Is there an ETA for this?

**Comment by antont** [comment]
> Is there an ETA for this?

Tiangolo has worked hard to bring FastAPI over to Pydantic v2. That's pretty far, and there he says, 4d ago, that he'll update SQLModel next. https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6387149

**Comment by honglei** [comment]
Some suggestions:

1, support sqlalchemy [mapped_column()](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.mapped_column), [Mapped](https://docs.sqlalchemy.org/en/20/orm/internals.html#sqlalchemy.orm.Mapped) or [Column](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Column) and lambda to avoid [column object already assigned to table](https://github.com/sqlalchemy/sqlalchemy/issues/5669#top)

2, support pydantic v2 [types](https://docs.pydantic.dev/latest/api/types/) and [network types](https://docs.pydantic.dev/latest/api/networks/)

3, support Annotated types or more...

4, Open a new branch for pydantic v2 and sqlalchemy v2?
https://github.com/tiangolo/sqlmodel/pull/632

samples:
```py3
from sqlmodel import SQLModel, Field
from typing_extensions import Annotated
from typing import Optional
from pydantic import AnyUrl, UrlConstraints
from pydantic.main import BaseModel
MoveSharedUrl =  Annotated[AnyUrl, UrlConstraints(max_length=512, allowed_schemes=['smb', 'ftp','file'])]

from sqlalchemy import Integer, Column, String
from sqlalchemy.orm import mapped_column
from ipaddress import IPv4Address, IPv6Address

class Sample(SQLModel, table=True):
    #1，
    union_str : str | None = Field( description='the name', primary_key=True)
    
    #2,
    optional_str: Optional[str] = Field( )
    
    #3, annotated Field with default value
    rateMax: Annotated[int , Field( sa_column= lambda: Column(Integer, default=-1, server_default="-1", nullable=False), ge=-1, description="")] = -1
    
    #4, pydantic annotated AnyUrl
    annotated_url: MoveSharedUrl = Field(description='the url')
    union_annotated_url: MoveSharedUrl |None = Field(description='the url')
    #5, python type to sqlalchemy type
    source_ip: IPv4Address | IPv6Address = Field(
        sa_column=mapped_column(String),
        description="source IP"
    )
```

**Comment by honglei** [comment]
A pull has been made for suport my sample: https://github.com/mbsantiago/sqlmodel/pull/1

**Comment by gnthibault** [comment]
I Is there a release date for sqlmodel fully compatible with latest version (>2) of pydantic ?

**Comment by AntonDeMeester** [comment]
> I Is there a release date for sqlmodel fully compatible with latest version (>2) of pydantic ?


> > Is there an ETA for this?
> 
> Tiangolo has worked hard to bring FastAPI over to Pydantic v2. That's pretty far, and there he says, 4d ago, that he'll update SQLModel next. [tiangolo/fastapi#9709 (reply in thread)](https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6387149)

Not yet, but it's on his todo list

**Comment by farridav** [comment]
Any movement on this ? Thanks for great work so far

**Comment by jorisgu** [comment]
Hi there, 
@tiangolo can we help you on this transition ? What could save you some time here ? 
Pydantic V2 is useful independently of SQLModel but any project with SQLModel is stuck behind.

**Comment by andrewshvv** [comment]
From https://github.com/tiangolo/sqlmodel/issues/654

> This is a tentative roadmap, I will update it as things evolve. Some things might be discarded, others might be added later. I didn't want to make it fully public as it could raise expectations, but it seems it would be more beneficial for the community to know all the ideas and objectives.

> Now, here's the current high-level tentative roadmap:
> 
>  Support for the latest SQLAlchemy before 2.0.
>  Support for SQLAlchemy 2.0.
>  Support for Pydantic 2.0.

**Comment by pmithrandir** [comment]
Maybe a silly idea, but in order to liberate the people using sqlmodel to use pydantic V2 on other part of the application, could you make the transition to use the embeded v1 present in V2 ?

That would allow dev to import pydantic V2, but to keep sqlmodel connected to pydantic V1 until it's ready.

**Comment by AntonDeMeester** [comment]
@pmithrandir @tiangolo has fixed this and both support is now integrated in the master branch. So you can use v2 for everything now

**Comment by JBorrow** [comment]
Should this issue not be closed now that v0.0.14 is out and supports pydantic v2?

**Comment by rcaught** [comment]
https://github.com/fastapi/sqlmodel/discussions/735

**Comment by YuriiMotov** [comment]
SQLModel supports Pydantic V2 since 0.0.14 (https://github.com/fastapi/sqlmodel/pull/722) 🎉
