### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class when having a field with a complex type

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [tiangolo/sqlmodel#67]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from datetime import datetime
from typing import Optional, List, Tuple, Dict, Union
from sqlmodel import Field, SQLModel, create_engine

class SemanticSearch(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    id_user: int
    date_time: datetime
    query: str
    clean_query: str
    semantic_search_result: List[Tuple[int, Dict[str, Union[str, int, float]]]]

## sqlite
sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url, echo=True)

SQLModel.metadata.create_all(engine)
```

### Description

I would like to create a `semantic_search` table in the `database.db` sqlite database with the 6 fields specified.

The last field `semantic_search_result` with `List[Tuple[int, Dict[str, Union[str, int, float]]]]` type seems to cause the error.

`semantic_search_result` looks like this for example:
```
[
   (0, { "acquisCode": str, "code": str, "level": int, "title": str, "similarity_score": float}),
   (1, { "acquisCode": str, "code": str, "level": int, "title": str, "similarity_score": float}),
   (2, { "acquisCode": str, "code": str, "level": int, "title": str, "similarity_score": float})
]
```
When running the code I got the following error:
```
Traceback (most recent call last):
  File "/home/matthieu/Code/Python/fastapi-graphql/test_SQLModel.py", line 6, in <module>
    class SemanticSearch(SQLModel, table=True):
  File "/home/matthieu/anaconda3/envs/sts-transformers-gpu-fresh/lib/python3.8/site-packages/sqlmodel/main.py", line 292, in __new__
    col = get_column_from_field(v)
  File "/home/matthieu/anaconda3/envs/sts-transformers-gpu-fresh/lib/python3.8/site-packages/sqlmodel/main.py", line 415, in get_column_from_field
    sa_type = get_sqlachemy_type(field)
  File "/home/matthieu/anaconda3/envs/sts-transformers-gpu-fresh/lib/python3.8/site-packages/sqlmodel/main.py", line 373, in get_sqlachemy_type
    if issubclass(field.type_, str):
TypeError: issubclass() arg 1 must be a class
```
I couldn't find a solution but #57 seems to have the same problem since having the same error.

### Operating System

Linux

### Operating System Details

Ubuntu 18.04 LTS

### SQLModel Version

0.0.4

### Python Version

3.8.8

**Comment by adem-usta** [comment]
🆙

**Comment by Matthieu-Tinycoaching** [comment]
Up!

**Comment by bjoernh** [comment]
same Problem

**Comment by txemac** [comment]
same problem here!

**Comment by data-djinn** [comment]
🆙
thank you to the maintainers & contributors of this awesome library!

**Comment by memark** [comment]
Any update on this issue?

**Comment by yallxe** [comment]
Same problem when doing `int | None` type. Workaround for this: `Optional[int]`.

**Comment by SPablo2191** [comment]
same happen using UUID4 for id

**Comment by ShravanSunder** [comment]
Its because of the `get_sqlachemy_type`. 

![2024-06-13 0602 Brave Browser TypeError issubclass() arg 1 must be a class when having a field with a complex type · Issue #67 · tiangolosqlmodel](https://github.com/tiangolo/sqlmodel/assets/5294949/69da254d-7ec5-4f9b-9a2c-4d8a1429bbea)

**Comment by YuriiMotov** [comment]
You need to specify the column type for SQLAlchemy (`Field(sa_type=JSON)` in this case):

```py
    semantic_search_result: List[Tuple[int, Dict[str, Union[str, int, float]]]] = Field(
        sa_type=JSON
    )

```

Runnable code example in the details:

<details>

```py
from typing import Dict, List, Optional, Tuple, Union

from sqlmodel import JSON, Field, Session, SQLModel, create_engine


class SemanticSearch(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    ...
    semantic_search_result: List[Tuple[int, Dict[str, Union[str, int, float]]]] = Field(
        sa_type=JSON
    )


## sqlite
sqlite_url = "sqlite:///"
engine = create_engine(sqlite_url, echo=True)


def main():
    SQLModel.metadata.create_all(engine)

    with Session(engine) as session:
        ss = SemanticSearch(
            semantic_search_result=[
                (2, {"acquis_code": "asd"}),
                (1, {"acquis_code": "qwerty"}),
            ]
        )
        session.add(ss)
        session.commit()

    with Session(engine) as session:
        ss_db = session.get(SemanticSearch, 1)
        assert ss_db.semantic_search_result[0][0] == 2
        assert ss_db.semantic_search_result[0][1]["acquis_code"] == "asd"
        assert ss_db.semantic_search_result[1][0] == 1
        assert ss_db.semantic_search_result[1][1]["acquis_code"] == "qwerty"


if __name__ == "__main__":
    main()

```

</details>
